sudo: required
language: node_js
node_js:
  - "10"
jobs:
  include:
    - stage: test
      name: "copr build test"
      script:
        - export SPEC=srcmap-reverse.spec
        - docker run -it -e SPEC="$SPEC" -e LOCAL_ONLY="True" -v $(pwd):/build:rw imlteam/copr
        - ((`find _topdir/RPMS -name *.rpm | wc -l` > 0))
    - stage: test
      name: "unit test"
      before_install:
        - npm i -g npm@latest codecov
      script: 
        - npm run cover
      after_success:
        - codecov
    - stage: test
      name: "integration test"
      before_install:
        - npm i -g npm@latest
      script: 
        - npm run integration-test
    - stage: deploy-npm
      name: "npm deploy"
      script:
        - npm pub
    - stage: cd
      name: "Continuous Deployment"
      script:
        - export OWNER=managerforlustre
        - export PROJECT=manager-for-lustre-devel
        - export PACKAGE=iml-srcmap-reverse
        - export SPEC=srcmap-reverse.spec
        - docker run -it -e OWNER="$OWNER" -e PROJECT="$PROJECT" -e PACKAGE="$PACKAGE" -e SPEC="$SPEC" -e KEY="$encrypted_253525cedcf6_key" -e IV="$encrypted_253525cedcf6_iv" -v $(pwd):/build:rw imlteam/copr
    - stage: deploy-copr-r5.0
      name: "Copr deploy"
      script:
        - export OWNER=managerforlustre
        - export PROJECT=manager-for-lustre-5.0
        - export PACKAGE=iml-srcmap-reverse
        - export SPEC=srcmap-reverse.spec
        - docker run -it -e OWNER="$OWNER" -e PROJECT="$PROJECT" -e PACKAGE="$PACKAGE" -e SPEC="$SPEC" -e PROD=true -e KEY="$encrypted_253525cedcf6_key" -e IV="$encrypted_253525cedcf6_iv" -v $(pwd):/build:rw imlteam/copr
stages:
  - test
  - name: cd
    if: branch = master AND type = push AND fork = false
  - name: deploy-npm
    if: branch =~ ^v\d+\.\d+\.\d+$
  - name: deploy-copr-r5.0
    if: branch =~ ^v\d+\.\d+\.\d+-.+-r5\.0$
