version: "3"
services:
  srcmap_reverse:
    build:
      context: .
    image: srcmap-reverse
    volumes:
      - ./test/fixtures/built-fd5ce21b.js.map.json:/tmp/built-fd5ce21b.js.map.json
    environment:
      - NODE_ENV=production
      - SRCMAP_REVERSE_PORT=8080
      - SOURCE_MAP_PATH=/tmp/built-*.js.map.json
    ports:
      - "8080:8080"